#---------------------------
# 全局
#---------------------------

# 用于浏览器标签的图标
favicon: /img/global/favicon.png

# 用于苹果设备的图标
apple_touch_icon: /img/global/favicon.png

# 强制所有链接升级为 HTTPS（适用于图片等资源出现 HTTP 混入报错）
force_https: true

# 主题暗色模式，开启后菜单中会出现切换按钮，用户浏览器会存储切换选项，并且会遵循 prefers-color-scheme 自动切换
dark_mode:
  default: dark

# 自定义 <head> 节点中的 HTML 内容
custom_head: '<link rel="alternate" type="application/atom+xml" title="Matrix53 的博客" href="https://matrix53.github.io/atom.xml">'

# 网页访问统计
web_analytics:  # 网页访问统计
  enable: true

  # LeanCloud 计数统计，可用于 PV UV 展示，如果 `web_analytics: enable` 没有开启，PV UV 展示只会查询不会增加
  leancloud:
    app_id: pel57WAJITy5XdQe8V6fpT70-gzGzoHsz
    app_key: G4sEBjAk4dmemxKj675Vse7I
    # REST API 服务器地址，国际版不填
    server_url: https://pel57waj.lc-cn-n1-shared.com


#---------------------------
# 页头
#---------------------------

# 导航栏的相关配置
navbar:
  # 导航栏左侧的标题，为空则按 hexo config 中 `title` 显示
  blog_title: "Matrix53"

  # 导航栏菜单，可自行增减，key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值；icon 是 css class，可以省略；增加 name 可以强制显示指定名称
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }
    - { key: "订阅", link: "/atom.xml", icon: "iconfont icon-rss" }


#---------------------------
# 页脚
#---------------------------
footer:
  # 展示网站的 PV、UV 统计数
  statistics:
    enable: true
    source: "leancloud"


#---------------------------
# 首页
#---------------------------
index:
  # 首页 Banner 头图，可以是相对路径或绝对路径，以下相同
  banner_img: /img/global/banner.jpg

  # 首页副标题的独立设置
  slogan:
    # 为空则按 hexo config.subtitle 显示
    text: "一只遵循KISS原则的前端"


#---------------------------
# 文章页
#---------------------------
post:
  banner_img: /img/global/banner.jpg

  # 文章在首页的默认封面图，当没有指定 index_img 时会使用该图片，若两者都为空则不显示任何图片
  default_index_img: /img/global/default_index.png

  # 文章标题下方的元信息
  meta:
    # 浏览量计数
    views:
      enable: true
      # 统计数据来源
      source: "leancloud"

  # 在文章开头显示文章更新时间，该时间默认是 md 文件更新时间，可通过 front-matter 中 `updated` 手动指定（和 date 一样格式）
  updated:
    enable: true

  # 评论插件
  comments:
    enable: true
    # 指定的插件，需要同时设置对应插件的必要参数
    type: utterances

  # 数学公式渲染
  math:
    enable: true
    specific: true
    engine: mathjax


#---------------------------
# 评论插件
#
# 开启评论需要先设置上方 `post: comments: enable: true`，然后根据 `type` 设置下方对应的评论插件参数
#---------------------------

# Utterances
# 基于 GitHub Issues
# See: https://utteranc.es
utterances:
  repo: Matrix53/Matrix53.github.io
  issue_term: title
  label: utterances
  theme: github-light
  theme_dark: github-dark
  crossorigin: anonymous


#---------------------------
# 分类页
#---------------------------
category:
  banner_img: /img/global/banner.jpg


#---------------------------
# 关于页
#---------------------------
about:
  banner_img: /img/global/banner.jpg
  subtitle:
  avatar: /img/global/avatar.png
  name: "Matrix53"
  intro: "KISS"
  # 更多图标可从 https://hexo.fluid-dev.com/docs/icon/ 查找，`class` 代表图标的 css class，添加 `qrcode` 后，图标不再是链接而是悬浮二维码
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/Matrix53", tip: "GitHub" }
    - { class: "iconfont icon-stack-overflow-fill",link: "https://stackoverflow.com/users/12389770/matrix53", tip: "StackOverflow" }
    - { class: "iconfont icon-zhihu-fill", link: "https://www.zhihu.com/people/gai-yong-hu-hen-lan-8-44", tip: "知乎" }
    - { class: "iconfont icon-wechat-fill", qrcode: "/img/global/wxQRcode_add.jpg" }


#---------------------------
# 友链页
#---------------------------
links:
  banner_img: /img/global/banner.jpg
  # 友链的成员项
  items:
    - {
      title: "Bflame",
      intro: "Never extinguish the Flame in my heart",
      link: "https://blog.bflame.studio",
      avatar: "https://bu.dusays.com/2021/07/24/2bd9226c10020.jpg"
    }
    - {
      title: "Marvolo",
      intro: "一枚随处可见的软件工程专业的普通大三学生",
      link: "http://marvolo.top",
      avatar: "https://avatars.githubusercontent.com/u/19513234?v=4"
    }
    - {
      title: "Zewan",
      intro: "Keep hungry and humble",
      link: "https://blog.zewan.cc",
      avatar: "https://bu.dusays.com/2021/07/24/ff9046ef4d517.jpg"
    }

  # 当成员头像加载失败时，替换为指定图片
  onerror_avatar: /img/avatar.png


#---------------------------
# 以下是配置 JS CSS 等静态资源的 URL 前缀，可以自定义成 CDN 地址，
#---------------------------

static_prefix:
  mathjax: https://lib.baomitu.com/mathjax/3.2.1/es5/
