#---------------------------
# 全局
#---------------------------

# 用于浏览器标签的图标
favicon: /img/global/favicon.png

# 用于苹果设备的图标
apple_touch_icon: /img/global/favicon.png

# 浏览器标签页中的标题分隔符，效果： 文章名 - 站点名
tab_title_separator: " - "

# 强制所有链接升级为 HTTPS（适用于图片等资源出现 HTTP 混入报错）
force_https: true

# 代码块的增强配置
code:
  # 是否开启复制代码的按钮
  copy_btn: true

  # 代码高亮
  highlight:
    enable: true

    # 代码块是否显示行号
    line_number: true

    # 实现高亮的库
    lib: "highlightjs"

    highlightjs:
      # 在链接中挑选 style 填入
      # See: https://highlightjs.org/static/demo/
      style: "Github Gist"

      # 是否根据 style 改变代码背景色（如果 style 是深色背景别忘了开启此项）
      bg_color: true

# 一些好玩的功能
fun_features:
  # 为 subtitle 添加打字机效果
  typing:
    enable: true

    # 打印速度，数字越大越慢
    typeSpeed: 70

    # 游标字符
    cursorChar: "_"

    # 是否循环播放效果
    loop: false

  # 为文章内容中的标题添加锚图标
  anchorjs:
    enable: true
    element: h1,h2,h3,h4,h5,h6
    placement: right
    # Options: hover | always | touch
    visible: hover
    # Option：§ | # | ❡
    icon: ""

  # 加载进度条
  progressbar:
    enable: true
    height_px: 3
    color: "#29d"
    # See: https://github.com/rstacruz/nprogress
    options: { showSpinner: false, trickleSpeed: 100 }

# 主题暗色模式，开启后菜单中会出现切换按钮，用户浏览器会存储切换选项，并且会遵循 prefers-color-scheme 自动切换
dark_mode:
  enable: true
  # Options: auto | light | dark
  default: dark

# 主题颜色配置，其他不生效的地方请使用自定义 css 解决，配色可以在下方链接中获得启发
# See: https://www.webdesignrankings.com/resources/lolcolors/
color:
  # body 背景色
  body_bg_color: "#eee"
  # 暗色模式下的 body 背景色，下同
  body_bg_color_dark: "#181c27"

  # 顶部菜单背景色
  navbar_bg_color: "#2f4154"
  navbar_bg_color_dark: "#1f3144"

  # 顶部菜单字体色
  navbar_text_color: "#fff"
  navbar_text_color_dark: "#d0d0d0"

  # 全局字体色
  text_color: "#3c4858"
  text_color_dark: "#c4c6c9"

  # 全局次级字体色（摘要、简介等位置）
  sec_text_color: "#718096"
  sec_text_color_dark: "#a7a9ad"

  # 文章正文字体色
  post_text_color: "#2c3e50"
  post_text_color_dark: "#c4c6c9"

  # 文章正文字体色（h1 h2 h3...）
  post_heading_color: "#1a202c"
  post_heading_color_dark: "#c4c6c9"

  # 文章超链接字体色
  post_link_color: "#0366d6"
  post_link_color_dark: "#1589e9"

  # 超链接悬浮时字体色
  link_hover_color: "#30a9de"
  link_hover_color_dark: "#30a9de"

  # 超链接悬浮背景色
  link_hover_bg_color: "#f8f9fa"
  link_hover_bg_color_dark: "#364151"

  # 主面板背景色
  board_color: "#fff"
  board_color_dark: "#252d38"

# 主题字体配置
font:
  font_size: 16px
  font_family:
  code_font_size: 85%

# 指定自定义 .js 文件路径，支持列表；路径是相对 source 目录，如 /js/custom.js 对应存放目录 source/js/custom.js
custom_js:

# 指定自定义 .css 文件路径，用法和 custom_js 相同
custom_css:

# 自定义 <head> 节点中的 HTML 内容
custom_head: '<link rel="alternate" type="application/atom+xml" title="Matrix53 的博客" href="https://matrix53.github.io/atom.xml">'

# 自定义底部 HTML 内容（位于 footer 上方），注意不要和 `post: custom` 配置冲突
custom_html: ''

# 网页访问统计
web_analytics:  # 网页访问统计
  enable: true

  # LeanCloud 计数统计，可用于 PV UV 展示，如果 `web_analytics: enable` 没有开启，PV UV 展示只会查询不会增加
  leancloud:
    app_id: pel57WAJITy5XdQe8V6fpT70-gzGzoHsz
    app_key: G4sEBjAk4dmemxKj675Vse7I
    # REST API 服务器地址，国际版不填
    # Only the Chinese mainland users need to set
    server_url:

# 对页面中的图片和评论插件进行懒加载处理，可见范围外的元素不会提前加载
lazyload:
  enable: true

  # 加载时的占位图片
  loading_img: /img/loading.gif

  # 开启后懒加载仅在文章页生效，如果自定义页面需要使用，可以在 Front-matter 里指定 `lazyload: true`
  onlypost: false

  # 触发加载的偏移倍数，基数是视窗高度，可根据部署环境的请求速度调节
  offset_factor: 2

# 图标库，包含了大量社交类图标，主题依赖的不包含在内，因此可自行修改，详见 https://hexo.fluid-dev.com/docs/icon/
iconfont: //at.alicdn.com/t/font_1736178_kmeydafke9r.css


#---------------------------
# 页头
#---------------------------

# 导航栏的相关配置
navbar:
  # 导航栏左侧的标题，为空则按 hexo config 中 `title` 显示
  blog_title: "Matrix53"

  # 导航栏菜单，可自行增减，key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值；icon 是 css class，可以省略；增加 name 可以强制显示指定名称
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }
    - { key: "订阅", link: "/atom.xml", icon: "iconfont icon-rss" }

# 搜索功能，基于 hexo-generator-search 插件，若已安装其他搜索插件请关闭此功能，以避免生成多余的索引文件
search:
  enable: true

  # 搜索索引文件的路径，可以是相对路径或外站的绝对路径
  path: /local-search.xml

  # 文件生成在本地的位置，必须是相对路径
  generate_path: /local-search.xml

  # 搜索的范围
  # Options: post | page | all
  field: post

  # 搜索是否扫描正文
  content: true

# 首屏图片的相关配置
banner:
  # 视差滚动，图片与板块会随着屏幕滚动产生视差效果
  parallax: true

  # 图片最小的宽高比，以免图片两边被过度裁剪，适用于移动端竖屏时，如需关闭设为 0
  width_height_ratio: 1.0

# 向下滚动的箭头
scroll_down_arrow:
  enable: true

  # 头图高度不小于指定比例，才显示箭头
  # Available: 0 - 100
  banner_height_limit: 80

  # 翻页后自动滚动
  scroll_after_turning_page: true

# 向顶部滚动的箭头
scroll_top_arrow:
  enable: true


#---------------------------
# 页脚
#---------------------------
footer:
  # 页脚第一行文字的 HTML，建议保留 Fluid 的链接，用于向更多人推广本主题
  content: '<a href="https://hexo.io" target="_blank" rel="nofollow noopener"><span>Hexo</span></a><i class="iconfont icon-love"></i><a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a>'

  # 展示网站的 PV、UV 统计数
  statistics:
    enable: true

    # 统计数据来源，使用 leancloud 需要设置 `web_analytics: leancloud` 中的参数；使用 busuanzi 不需要额外设置，但是有时不稳定，另外本地运行时 busuanzi 显示统计数据很大属于正常现象，部署后会正常
    # Options: busuanzi | leancloud
    source: "leancloud"

    # 页面显示的文本，{}是数字的占位符（必须包含)，下同
    pv_format: "总访问量 {} 次"
    uv_format: "总访客数 {} 人"


#---------------------------
# 首页
#---------------------------
index:
  # 首页 Banner 头图，可以是相对路径或绝对路径，以下相同
  banner_img: /img/global/banner.jpg

  # 头图高度，屏幕百分比
  # Available: 0 - 100
  banner_img_height: 100

  # 头图黑色蒙版的不透明度，available: 0 - 1.0， 1 是完全不透明
  # Available: 0 - 1.0
  banner_mask_alpha: 0.3

  # 首页副标题的独立设置
  slogan:
    enable: true

    # 为空则按 hexo config.subtitle 显示
    text: "一只遵循KISS原则的前端"

  # 自动截取文章摘要
  auto_excerpt:
    enable: true

  # 打开文章的标签方式
  # Available: _blank | _self
  post_url_target: _self

  # 是否显示文章信息（时间、分类）
  post_meta:
    date: true
    category: true

  # 文章通过 sticky 排序后，在首页文章标题前显示图标
  post_sticky:
    enable: true
    icon: "iconfont icon-top"


#---------------------------
# 文章页
#---------------------------
post:
  banner_img: /img/global/banner.jpg
  banner_img_height: 70
  banner_mask_alpha: 0.3

  # 文章在首页的默认封面图，当没有指定 index_img 时会使用该图片，若两者都为空则不显示任何图片
  default_index_img: /img/global/default_index.png

  # 文章标题下方的元信息
  meta:
    # 作者，优先根据 front-matter 里 author 字段，其次是 hexo 配置中 author 值
    author:
      enable: false

    # 文章日期，优先根据 front-matter 里 date 字段，其次是 md 文件日期
    date:
      enable: true
      # 格式参照 ISO-8601 日期格式化
      # See: http://momentjs.cn/docs/#/parsing/string-format/
      format: "LL a"

    # 字数统计
    wordcount:
      enable: true
      # 显示的文本，{}是数字的占位符（必须包含)，下同
      format: "{} 字"

    # 估计阅读全文需要的时长
    min2read:
      enable: true
      format: "{} 分钟"
      # 每分钟阅读多少字，如果是技术文章，建议降低
      words: 100

    # 浏览量计数
    views:
      enable: true
      # 统计数据来源
      # Options: busuanzi | leancloud
      source: "leancloud"
      format: "{} 次"

  # 在文章开头显示文章更新时间，该时间默认是 md 文件更新时间，可通过 front-matter 中 `updated` 手动指定（和 date 一样格式）
  updated:
    enable: true

    # 描述文字
    content: 本文最后更新于：

    # 是否使用相对时间表示，比如："3 天前"
    relative: false

  # 文章右侧目录
  toc:
    enable: true
    # 目录会选择这些节点作为标题
    headingSelector: "h1,h2,h3,h4,h5,h6"
    # 层级的折叠深度，0 是全部折叠，大于 0 后如果存在下级标题则默认展开
    collapseDepth: 0

  # 版权声明，会显示在每篇文章的结尾
  copyright:
    enable: true

  # 文章底部上一篇下一篇功能
  prev_next:
    enable: true

  # 文章底部自定义区域（位于 footer 上方），支持 HTML，可插入赞赏码、公众号这类内容
  custom:
    enable: false
    content: '<img src="https://octodex.github.com/images/jetpacktocat.png" class="rounded mx-auto d-block mt-5" style="width:150px; height:150px;">'

  # 文章图片可点击放大
  image_zoom:
    enable: true
    # 放大后图片链接替换规则，可用于将压缩图片链接替换为原图片链接，如 ['-slim', ''] 是将链接中 `-slim` 移除；如果想使用正则请使用 `re:` 前缀，如 ['re:\\d{3,4}\\/\\d{3,4}\\/', '']
    img_url_replace: ['', '']

  # 脚注语法，会在文章底部生成脚注，如果 Markdown 渲染器本身支持，则建议关闭，否则可能会冲突
  footnote:
    enable: true
    # 脚注的节标题，也可以在 front-matter 中通过 `footnote: <h2>Reference</h2>` 这种形式修改单独页面的 header
    header: ''

  # 评论插件
  comments:
    enable: true
    # 指定的插件，需要同时设置对应插件的必要参数
    # Options: utterances | disqus | gitalk | valine | waline | changyan | livere | remark42 | twikoo | cusdis
    type: utterances

  # 数学公式渲染
  math:
    enable: true
    specific: true
    engine: mathjax


#---------------------------
# 评论插件
#
# 开启评论需要先设置上方 `post: comments: enable: true`，然后根据 `type` 设置下方对应的评论插件参数
#---------------------------

# Utterances
# 基于 GitHub Issues
# See: https://utteranc.es
utterances:
  repo: Matrix53/Matrix53.github.io
  issue_term: title
  label: utterances
  theme: github-light
  theme_dark: github-dark
  crossorigin: anonymous


#---------------------------
# 分类页
#---------------------------
category:
  enable: true
  banner_img: /img/global/banner.jpg
  banner_img_height: 60
  banner_mask_alpha: 0.3
  subtitle:

  # 分类的排序字段，前面带减号是倒序，不带减号是正序
  # Options: length | name
  order_by: "-length"

  # 层级的折叠深度，0 是全部折叠，大于 0 后如果存在子分类则默认展开
  collapse_depth: 0

  # 文章的排序字段，前面带减号是倒序，不带减号是正序
  # Options: date | title | or other field of front-matter
  post_order_by: "-date"

  # 单个分类中折叠展示文章数的最大值，超过限制会显示 More，0 则不限制
  post_limit: 10


#---------------------------
# 关于页
#---------------------------
about:
  enable: true
  banner_img: /img/global/banner.jpg
  banner_img_height: 60
  banner_mask_alpha: 0.3
  subtitle:
  avatar: /img/global/avatar.png
  name: "Matrix53"
  intro: "KISS"
  # 更多图标可从 https://hexo.fluid-dev.com/docs/icon/ 查找，`class` 代表图标的 css class，添加 `qrcode` 后，图标不再是链接而是悬浮二维码
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/Matrix53", tip: "GitHub" }
    - { class: "iconfont icon-stack-overflow-fill",link: "https://stackoverflow.com/users/12389770/matrix53", tip: "StackOverflow" }
    - { class: "iconfont icon-zhihu-fill", link: "https://www.zhihu.com/people/gai-yong-hu-hen-lan-8-44", tip: "知乎" }
    - { class: "iconfont icon-wechat-fill", qrcode: "/img/global/wxQRcode_add.jpg" }

#---------------------------
# 404页
#---------------------------
page404:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 85
  banner_mask_alpha: 0.3
  subtitle: "Page not found"


#---------------------------
# 友链页
#---------------------------
links:
  enable: true
  banner_img: /img/global/banner.jpg
  banner_img_height: 60
  banner_mask_alpha: 0.3
  subtitle:
  # 友链的成员项
  items:
    - {
      title: "Bflame",
      intro: "Never extinguish the Flame in my heart",
      link: "https://blog.bflame.studio",
      avatar: "https://bu.dusays.com/2021/07/24/2bd9226c10020.jpg"
    }
    - {
      title: "Marvolo",
      intro: "一枚随处可见的软件工程专业的普通大三学生",
      link: "http://marvolo.top",
      avatar: "https://avatars.githubusercontent.com/u/19513234?v=4"
    }
    - {
      title: "Zewan",
      intro: "Keep hungry and humble",
      link: "https://blog.zewan.cc",
      avatar: "https://bu.dusays.com/2021/07/24/ff9046ef4d517.jpg"
    }

  # 当成员头像加载失败时，替换为指定图片
  onerror_avatar: /img/avatar.png

  # 友链下方自定义区域，支持 HTML，可插入例如申请友链的文字
  custom:
    enable: false
    content: '<hr><p>在下方留言申请加入我的友链，按如下格式提供信息：</p><ul><li>博客名：Fluid</li><li>简介：Fluid 主题官方博客</li><li>链接：https://hexo.fluid-dev.com</li><li>图片：https://hexo.fluid-dev.com/img/favicon.png</li></ul>'

  # 评论插件
  comments:
    enable: false
    # 指定的插件，需要同时设置对应插件的必要参数
    # Options: utterances | disqus | gitalk | valine | waline | changyan | livere | remark42 | twikoo | cusdis
    type: disqus


#---------------------------
# 以下是配置 JS CSS 等静态资源的 URL 前缀，可以自定义成 CDN 地址，
# 默认的 jsDelivr CDN 可能在部分地区无法访问，如果需要修改，最好使用与默认配置相同的版本，以避免潜在的问题，
# ** 如果你不知道如何设置，请不要做任何改动 **
#---------------------------

static_prefix:
  # 内部静态
  internal_js: /js
  internal_css: /css
  internal_img: /img

  anchor: https://cdn.jsdelivr.net/npm/anchor-js@4/

  github_markdown: https://cdn.jsdelivr.net/npm/github-markdown-css@4/

  jquery: https://cdn.jsdelivr.net/npm/jquery@3/dist/

  bootstrap: https://cdn.jsdelivr.net/npm/bootstrap@4/dist/

  highlightjs: https://cdn.jsdelivr.net/npm/highlight.js@10/

  prismjs: https://cdn.jsdelivr.net/npm/prismjs@1/

  tocbot: https://cdn.jsdelivr.net/npm/tocbot@4/dist/

  typed: https://cdn.jsdelivr.net/npm/typed.js@2/lib/

  fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3/dist/

  nprogress: https://cdn.jsdelivr.net/npm/nprogress@0/

  mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/

  katex: https://cdn.jsdelivr.net/npm/katex@0/dist/

  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/

  clipboard: https://cdn.jsdelivr.net/npm/clipboard@2/dist/

  mermaid: https://cdn.jsdelivr.net/npm/mermaid@8/dist/

  valine: https://cdn.jsdelivr.net/npm/valine@1/dist/

  waline: https://cdn.jsdelivr.net/npm/@waline/client@1/dist/

  gitalk: https://cdn.jsdelivr.net/npm/gitalk@1/dist/

  disqusjs: https://cdn.jsdelivr.net/npm/disqusjs@1/dist/

  twikoo: https://cdn.jsdelivr.net/npm/twikoo@1/dist/

  hint: https://cdn.jsdelivr.net/npm/hint.css@2/
